const guestList = {
    "Corinne attal": "2",
    "Roger alezra": "2",
    "Chantal alezra": "2",
    "Betty benichou": "2",
    "Xavier benichou": "2",
    "Esther boudana": "2",
    "Raymond boudana": "2",
    "Karelle guez": "2",
    "Jean-Marc guez": "2",
    "Nathan sebbagh": "1",
    "Shiraz sebbagh": "1",
    "Frederic sebbagh": "1",
     "Isabelle sebbagh": "1",
    "Lea sebbagh": "1",
    "Noam sebbagh": "1",
    "Yaniv sebbagh": "1",
     "Perla Dialowsky": "1",
    "Ilan Dialowsky": "1",
    "Aviel attia": "1",
    "Odelia attia": "1",
     "Rivka chelli": "1",
    "Francine Marcovitch": "11",
    "Michel Sarfati": "11",
    "Tsefania Attal": "11",
     "Samuel Attal": "11",
    "Hanna Lagas": "10",
    "Avi Lagas": "10",
    "Chalom marouani": "10",
    "Joelle marouani": "10",
    "Jean-david attal": "11",
    "Abraham marouani": "3",
    "Mina marouani": "3",
    "Jean Dupont": "Table 5",
    "Maurice Baroukh": "5",
    "Noemie Baroukh": "5",
    "Chantal zerbib": "5",
    "Yves zerbib": "5",
    "Clement baroukh": "5",
    "Carole baroukh": "5",
    "Elie marouani": "5",
     "Valerie ifergan": "5",
    "Poupée baroukh": "5",
    "Benny bismuth": "11",
    "Yaffa bismuth": "11",
    "Corinne boukhris": "avec enfants ,11",
    "Hanni bitton": "3",
    "Elie marouani": "3",
    "Johnny marouani": "3",
     "Anastasia marouani": "3",
    "Itay Marouani": "3",
    "Nicole Marouani": "3",
    "Sylvain Zouari": "3",
     "Valerie zouari": "3",
    "Ilan Zouari": "3",
    "Sharon zouari": "3",
    "Julie fellous": "avec enfants, 4",
     "Esther goldstein": "4",
    "Hen goldstein": "4",
    "Yossi goldstein": "4",
    "Tarcine": "4",
     "Yaacov": "4",
    "Joelle piersak": "avec mari, 5",
    "Sabrina Baroukh": "5",
    "Myriam Benamhou": "12",
     "Jean-claude benamhou": "12",
    "Megane benamhou": "12",
    "Dan zerbib": "12",
    "Esther zerbib": "12",
     "Rachel benamhou": "12",
    "Michael benamhou": "12",
    "Nathalie perez": "12",
    "Serge perez": "12",
     "Shana perez": "12",
    "Dolly gluck": "15",
    "Jonathan gluck": "15",
    "Monique cohen": "15",
     "david cohen": "15",
    "henri cohen": "15",
    "shirel sberro": "15",
    "shai sberro": "15",
     "Eva nataf": "15",
    "Charly nataf": "15",
    "Liel nataf": "15",
    "Shirel nataf": "15",
     "rebbecca zerbib": "15",
    "Nathan zerbib": "15",
    "David marouani": "14",
    "Hanna marouani": "14",
     "Myriam gabriel": "14",
    "Elie gabriel": "14",
    "Sabrina marouani": "14",
    "Yardenna marouani": "14",
     "odelia marouani": "14",
    "elie marouani": "14",
    "Ruth elbaz": "14",
    "David elbaz": "14",
     "Celine peres ": "13",
    "Amiel peres": "13",
    "Jocelyne berdah": "13",
    "Ninette berdah": "13",
     "Tsion berdah": "13",
    "Ethy berdah": "13",
    "Maguy arfi": "12",
    "Yaron baroukh": "16",
     "Shaïly baroukh": "16",
    "Ron zerbib": "16",
    "oren zerbib": "16",
    "Liora baroukh": "16",
     "Daniel lagas": "16",
    "Salome guez": "16",
    "Léa guez": "16",
    "Sarah guez": "16",
     "Noa benichou": "16",
    "Lee benichou": "16",
    "Damek lagas": "10",
    "kassao lagas": "10",
     "sarah lagas": "10",
    "haim lagas": "10",
    "yaniv lagas": "10",
    "zehava lagas ": "10",
     "Adam marouani": "17",
    "Amir jeffrey": "17",
    "Anthony Roffe": "17",
    "Ariel sebagh": "17",
     "Ilan levy": "17",
    "Eden marciano": "17",
    "Or shalev": "17",
    "Yaacov amanou": "17",
     "nathanel amanou": "17",
    "Ethan marouani": "7",
    "Dan allouche": "+1, 7",
    "Ben ohana": "7",
     "Bar ohana": "7",
    "Ethan saban": "7",
    "Daniel braha": "7",
    "Yaniv gabote": "7",
     "Nathanel arbib": "7",
    "Ben aknine": "7",
    "Nadav mangisto": "7",
    "samuel sabag": "17",
     "shay vaisman": "17",
    "David copain ethan": "17",
    "Lyron benamhou": "9",
    "Sharone amar": "9",
     "Yoni benamhou": "9",
    "David benamhou": "9",
    "meir baroukh": "9",
    "noam baroukh": "9",
     "leana sebban": "9",
    "julia guili": "6",
    "sasha guez": "6",
    "johanna setrouk": "6",
     "elsa winkel": "6",
    "keren fettaya": "6",
    "jonathan fettaya": "6",
    "Shany timestit": "6",
     "rebbeca chemouny": "6",
    "nathan chemouny": "6",
    "noah lousky": "6",
    "daniel lousky": "6",
     "lisa arfi": "6",
    "liora elbaz": "6",
    "isaac elbaz": "6",
    "yonathan baroukh": "6",
     "Nathan medina": "+1, 6",
    "Ethan shimshon": "+1, 6",
    "Elior ": "6",
    "annaelle freoua": "8",
     "liron freoua": "8",
    "doron atlan": "8",
    "zachary atlan": "8",
    "ethan haouzi": "8",
     "aviel haouzi": "8",
    "yossi amouyal": "8",
    "ilan albo": "8",
    "eden ayache": "8",
     "liron benichou": "8",
    "michael dana": "+1, 8",
    "goel benfresh": "8",
    "greg benfresh": "8",
     "michel habib": "8",
    "dvir sharabani": "8",
    "viking": "8",
    "Samuel peres": "9",
     "doron peres": "9",
    "raphael peres": "9",
    "aurore breton": "18",
    "irena bogored": "18",
     "christina": "18",
    "meir cohen": "18",
    "doudi israel": "18",
    "noam": "18",
     "svetlana hanosvosky": "18",
    "Moshe handi": "17",
    "ilan shimshon": "18",
    "léa shimshon": "18",
     "corinne benichou": "18",
    "yaacov benichou": "18",
 
    // Ajoutez autant d'invités que nécessaire
};



 function findTable() {
  const guestName = document.getElementById('guestName').value.trim().toLowerCase();
   const resultDiv = document.getElementById('result');

    // Rechercher l'invité en ignorant la casse
   const foundGuest = Object.keys(guestList).find(name => name.toLowerCase() === guestName);

   if (foundGuest) {
       resultDiv.textContent = `${foundGuest},  ${guestList[foundGuest]}.`;
    } else {
       resultDiv.textContent = "Don't find, check the list";

;
   }
}